<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-RP7FE1C" name="com.webtest.lizhe.StoreConfiguration" tests="9" failures="1" timestamp="16 十二月 2019 13:32:02 GMT" time="124.949" errors="0">
  <testcase name="test8" time="12.912" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test9" time="15.726" classname="com.webtest.lizhe.StoreConfiguration">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.webtest.lizhe.StoreConfiguration.test9(StoreConfiguration.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test9 -->
  <testcase name="test7" time="13.440" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test3" time="12.900" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test1" time="9.943" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test5" time="14.644" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test4" time="20.965" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test6" time="14.426" classname="com.webtest.lizhe.StoreConfiguration"/>
  <testcase name="test2" time="9.993" classname="com.webtest.lizhe.StoreConfiguration"/>
</testsuite> <!-- com.webtest.lizhe.StoreConfiguration -->
